### ISSUE TITLE
Where's your source code? within 24 hr

### ISSUE THREAD

**Issue by TerraceFe** [araafroyall/Cleaner-Pro-Lite#15]
> Source Code will be available within 2 days

That's what you [said a week ago](https://github.com/araafroyall/Cleaner-Pro-Lite/issues/11#issuecomment-1752388775_), where's your source code other than those xml files? 

Trojan app confirmed lol

**Comment by araafroyall** [comment]
Dont use such words here.

Allow me some time , i am not free everytime.

I will surely upload all source code even with block based codes used by sketchware.

as this app developed using sketchware pro (do you know this)
 Go and make an app with this and try yourself.


So.. i need some time to upload them. within 24 hour. 

earlier i was busy in making v2.9 and updating telegram bot..

**Comment by araafroyall** [comment]
![Screenshot_2023-10-15-11-20-25-611_com sketchware remod](https://github.com/araafroyall/Cleaner-Pro-Lite/assets/87515236/59fd62a1-22bd-41cd-89db-3f1051ed7a7a)

 See i made this by Sketchware pro. go to github and know about it. 
there is no trojen in sketchware pro app.
if you need i can give you link

And to the point for my app source code.
i will surely provide within 24 hr. 
because it need some time to export from sketchware and upload to github ok

never use trojen word again with my app
if you dont want to use just go to goole and find better cleaner app than this. 
i am sure that you will never find better than this.

**Comment by araafroyall** [comment]
> > Source Code will be available within 2 days
> 
> That's what you [said a week ago](https://github.com/araafroyall/Cleaner-Pro-Lite/issues/11#issuecomment-1752388775_), where's your source code other than those xml files? 
> 
> Trojan app confirmed lol


Source Code is Now Available.

And never tell such trojan word here
